{
 "title": "Salezi",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All categories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average price by category",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "queryText": "SELECT 'Books' AS category, AVG(price) AS average_price FROM books\nUNION\nSELECT 'Electronics' AS category, AVG(price) AS average_price FROM electronics\nUNION\nSELECT 'DVDs' AS category, AVG(price) AS average_price FROM dvds;\n\n\n",
       "rawQueryText": "SELECT 'Books' AS category, AVG(price) AS average_price FROM books\nUNION\nSELECT 'Electronics' AS category, AVG(price) AS average_price FROM electronics\nUNION\nSELECT 'DVDs' AS category, AVG(price) AS average_price FROM dvds;\n\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Total quantity by category",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT 'CDs' AS category, SUM(quantity) FROM dvds\nUNION ALL\nSELECT 'Books' AS category, SUM(quantity) FROM books\nUNION ALL\nSELECT 'Electronics' AS category, SUM(quantity) FROM electronics\n\n\n",
       "rawQueryText": "SELECT 'CDs' AS category, SUM(quantity) FROM dvds\nUNION ALL\nSELECT 'Books' AS category, SUM(quantity) FROM books\nUNION ALL\nSELECT 'Electronics' AS category, SUM(quantity) FROM electronics\n\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Average quantity by category",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "queryText": "SELECT 'Books' AS category, AVG(quantity) AS average_quantity FROM books\nUNION\nSELECT 'Electronics' AS category, AVG(quantity) AS average_quantity FROM electronics\nUNION\nSELECT 'DVDs' AS category, AVG(quantity) AS average_quantity FROM dvds;\n\n\n",
       "rawQueryText": "SELECT 'Books' AS category, AVG(quantity) AS average_quantity FROM books\nUNION\nSELECT 'Electronics' AS category, AVG(quantity) AS average_quantity FROM electronics\nUNION\nSELECT 'DVDs' AS category, AVG(quantity) AS average_quantity FROM dvds;\n\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Sellers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total of product by categories per sellers",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "queryText": "SELECT\n    sellers.name,\n    COUNT(DISTINCT books.id) AS total_books,\n    COUNT(DISTINCT electronics.id) AS total_electronics,\n    COUNT(DISTINCT dvds.id) AS total_dvds\nFROM\n    sellers\nLEFT JOIN\n    sellers_books_links ON sellers.id = sellers_books_links.seller_id\nLEFT JOIN\n    books ON sellers_books_links.book_id = books.id\nLEFT JOIN\n    sellers_electronics_links ON sellers.id = sellers_electronics_links.seller_id\nLEFT JOIN\n    electronics ON sellers_electronics_links.electronic_id = electronics.id\nLEFT JOIN\n    sellers_dvds_links ON sellers.id = sellers_dvds_links.seller_id\nLEFT JOIN\n    dvds ON sellers_dvds_links.dvd_id = dvds.id\nGROUP BY\n    sellers.id, sellers.name;\n",
       "rawQueryText": "SELECT\n    sellers.name,\n    COUNT(DISTINCT books.id) AS total_books,\n    COUNT(DISTINCT electronics.id) AS total_electronics,\n    COUNT(DISTINCT dvds.id) AS total_dvds\nFROM\n    sellers\nLEFT JOIN\n    sellers_books_links ON sellers.id = sellers_books_links.seller_id\nLEFT JOIN\n    books ON sellers_books_links.book_id = books.id\nLEFT JOIN\n    sellers_electronics_links ON sellers.id = sellers_electronics_links.seller_id\nLEFT JOIN\n    electronics ON sellers_electronics_links.electronic_id = electronics.id\nLEFT JOIN\n    sellers_dvds_links ON sellers.id = sellers_dvds_links.seller_id\nLEFT JOIN\n    dvds ON sellers_dvds_links.dvd_id = dvds.id\nGROUP BY\n    sellers.id, sellers.name;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Average products price per seller",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "queryText": "SELECT\n    sellers.name AS seller_name,\n    AVG(COALESCE(books.price, electronics.price, dvds.price)) AS average_price\nFROM\n    sellers\nLEFT JOIN\n    sellers_books_links ON sellers.id = sellers_books_links.seller_id\nLEFT JOIN\n    books ON sellers_books_links.book_id = books.id\nLEFT JOIN\n    sellers_electronics_links ON sellers.id = sellers_electronics_links.seller_id\nLEFT JOIN\n    electronics ON sellers_electronics_links.electronic_id = electronics.id\nLEFT JOIN\n    sellers_dvds_links ON sellers.id = sellers_dvds_links.seller_id\nLEFT JOIN\n    dvds ON sellers_dvds_links.dvd_id = dvds.id\nGROUP BY\n    sellers.id, seller_name;\n",
       "rawQueryText": "SELECT\n    sellers.name AS seller_name,\n    AVG(COALESCE(books.price, electronics.price, dvds.price)) AS average_price\nFROM\n    sellers\nLEFT JOIN\n    sellers_books_links ON sellers.id = sellers_books_links.seller_id\nLEFT JOIN\n    books ON sellers_books_links.book_id = books.id\nLEFT JOIN\n    sellers_electronics_links ON sellers.id = sellers_electronics_links.seller_id\nLEFT JOIN\n    electronics ON sellers_electronics_links.electronic_id = electronics.id\nLEFT JOIN\n    sellers_dvds_links ON sellers.id = sellers_dvds_links.seller_id\nLEFT JOIN\n    dvds ON sellers_dvds_links.dvd_id = dvds.id\nGROUP BY\n    sellers.id, seller_name;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Electronics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "% par brand",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n    electronics.brand AS brand_name,\n    COUNT(electronics.id) AS total_electronics\nFROM\n    electronics\nGROUP BY\n    electronics.brand\nORDER BY\n    total_electronics DESC;",
       "rawQueryText": "SELECT\n    electronics.brand AS brand_name,\n    COUNT(electronics.id) AS total_electronics\nFROM\n    electronics\nGROUP BY\n    electronics.brand\nORDER BY\n    total_electronics DESC;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Quantity of electronics",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 8, "y": 3 },
     "targets": [
      {
       "queryText": "SELECT name, \"-\", brand, quantity from electronics",
       "rawQueryText": "SELECT name, \"-\", brand, quantity from electronics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "% of each type of product",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n    electronics.type AS type_name,\n    COUNT(electronics.id) AS total_electronics\nFROM\n    electronics\nGROUP BY\n    electronics.type \nORDER BY\n    total_electronics DESC;",
       "rawQueryText": "SELECT\n    electronics.type AS type_name,\n    COUNT(electronics.id) AS total_electronics\nFROM\n    electronics\nGROUP BY\n    electronics.type \nORDER BY\n    total_electronics DESC;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Electronics price",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "queryText": "select name, \"-\", brand, price from electronics",
       "rawQueryText": "select name, \"-\", brand, price from electronics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Books", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Quantity of books",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "queryText": "SELECT name, \"-\" ,author, quantity from books",
     "rawQueryText": "SELECT name, \"-\" ,author, quantity from books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Books price",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 9, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "queryText": "SELECT name,\"-\", author, price from books",
     "rawQueryText": "SELECT name,\"-\", author, price from books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "% per author",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n    books.author AS author_name,\n    COUNT(books.id) AS total_books\nFROM\n    books\nGROUP BY\n    books.author\nORDER BY\n    total_books DESC;\n",
     "rawQueryText": "SELECT\n    books.author AS author_name,\n    COUNT(books.id) AS total_books\nFROM\n    books\nGROUP BY\n    books.author\nORDER BY\n    total_books DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "CDs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Quantity of CDs",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT name, \"-\" ,artist, quantity from dvds\n\n\n",
     "rawQueryText": "SELECT name, \"-\" ,artist, quantity from dvds\n\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CDs price",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 9, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "queryText": "SELECT name,\"-\", artist, price from dvds",
     "rawQueryText": "SELECT name,\"-\", artist, price from dvds",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "% per artist",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n    dvds.artist AS artist_name,\n    COUNT(dvds.id) AS total_dvds\nFROM\n    dvds\nGROUP BY\n    dvds.artist\nORDER BY\n    total_dvds DESC;\n",
     "rawQueryText": "SELECT\n    dvds.artist AS artist_name,\n    COUNT(dvds.id) AS total_dvds\nFROM\n    dvds\nGROUP BY\n    dvds.artist\nORDER BY\n    total_dvds DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}